CREATE TABLE IF NOT EXISTS columns(
    id INT NOT NULL AUTO_INCREMENT KEY,
    title VARCHAR(255),
    position DOUBLE NOT NULL,
    board_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (board_id) REFERENCES boards(id)
);