FROM golang:1.16

RUN mkdir /drello-api
WORKDIR /drello-api

RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY . .
RUN go install

# Connection to DB
ARG DB_USER
ENV DB_USER $DB_USER
ARG DB_PASS
ENV DB_PASS $DB_PASS
ARG DB_TCP_HOST
ENV DB_TCP_HOST $DB_TCP_HOST
ARG DB_PORT
ENV DB_PORT $DB_PORT
ARG DB_NAME
ENV DB_NAME $DB_NAME

ARG TEST_DB_USER
ENV TEST_DB_USER $TEST_DB_USER
ARG TEST_DB_PASS
ENV TEST_DB_PASS $TEST_DB_PASS
ARG TEST_DB_TCP_HOST
ENV TEST_DB_TCP_HOST $TEST_DB_TCP_HOST
ARG TEST_DB_PORT
ENV TEST_DB_PORT $TEST_DB_PORT
ARG TEST_DB_NAME
ENV TEST_DB_NAME $TEST_DB_NAME

ARG GOOGLE_APPLICATION_CREDENTIALS
ENV GOOGLE_APPLICATION_CREDENTIALS $GOOGLE_APPLICATION_CREDENTIALS

# Other environment variables
ARG SERVER_ENV
ENV SERVER_ENV $SERVER_ENV

# API server's endpoint
ARG PORT=8080
ENV PORT $PORT
EXPOSE $PORT

CMD ["go", "run", "."]