version: "3.8"
services:
  app:
    build:
      context: "."
      args:
        DB_USER: root
        DB_PASS: password
        DB_TCP_HOST: db
        DB_PORT: 3306
        DB_NAME: drello-dev
        TEST_DB_USER: root
        TEST_DB_PASS: password
        TEST_DB_TCP_HOST: db
        TEST_DB_PORT: 3306
        TEST_DB_NAME: drello-test
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ".:/drello-api"
  db:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/db/init.sql
    command: --init-file /db/init.sql

volumes:
  db-data: {}
