# on:
#   push:
#     branches:
#       - "main"
name: PR Check
on: pull_request

name: Deploy to Heroku at Production

jobs:
  deploy:
    name: Deploy to Heroku at Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app drello-api-dev
      - run: heroku container:login
      - run: heroku container:push web
      - run: heroku container:release web
