name: Deploy to Staging
on:
  push:
    branches:
      - "stg-**"

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.STG_HEROKU_APP_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create GOOGLE_APPLICATION_CREDENTIALS .json file
        run: echo "${{ env.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $APP_NAME
      - name: Log in to Heroku Container Registry
        run: heroku container:login
      - name: Build a Docker image
        run: docker build
          --no-cache
          -t registry.heroku.com/$APP_NAME/web
          --build-arg DB_USER=$STG_DB_USER
          --build-arg DB_PASS=$STG_DB_PASS
          --build-arg DB_TCP_HOST=$STG_DB_TCP_HOST
          --build-arg DB_PORT=$STG_DB_PORT
          --build-arg DB_NAME=$STG_DB_NAME .
        env:
          STG_DB_USER: ${{ secrets.STG_DB_USER }}
          STG_DB_PASS: ${{ secrets.STG_DB_PASS }}
          STG_DB_TCP_HOST: ${{ secrets.STG_DB_TCP_HOST }}
          STG_DB_PORT: ${{ secrets.STG_DB_PORT }}
          STG_DB_NAME: ${{ secrets.STG_DB_NAME }}
      - name: Push the image to Heroku
        run: docker push registry.heroku.com/$APP_NAME/web
      - name: Release the new image
        run: heroku container:release web -a $APP_NAME
