name: Deploy to Heroku at Production
on: pull_request

# on: push

# on:
#   push:
#     branches:
#       - "main"

jobs:
  deploy:
    name: Deploy to Heroku at Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app drello-api-dev
      - run: heroku container:login
      - run: docker build
          -t registry.heroku.com/drello-api-dev/web
          --build-arg DB_USER=$STG_DB_USER
          --build-arg DB_PASS=$STG_DB_PASS
          --build-arg DB_TCP_HOST=$STG_DB_TCP_HOST
          --build-arg DB_PORT=$STG_DB_PORT
          --build-arg DB_NAME=$STG_DB_NAME .
        env:
          DB_USER: ${{ secrets.STG_DB_USER }}
          DB_PASS: ${{ secrets.STG_DB_PASS }}
          DB_TCP_HOST: ${{ secrets.STG_DB_TCP_HOST }}
          DB_PORT: ${{ secrets.STG_DB_PORT }}
          DB_NAME: ${{ secrets.STG_DB_NAME }}
      # - run: heroku container:push web
      - run: docker push registry.heroku.com/drello-api-dev/web
      - run: heroku container:release web
