name: PR Check
on: pull_request

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: drello-test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 4306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./...
